from __future__ import annotations

from src.features.configuration.models import AdminSchema, FieldDefinition, FieldOption

ALARM_RULES_ADMIN_SCHEMA = AdminSchema(
    key='alarm_rules',
    title='Reglas de alarmas',
    fields=(
        FieldDefinition(
            name='rule_key',
            label='ID regla',
            field_type='text',
            required=True,
            editable=False,
        ),
        FieldDefinition(
            name='family_key',
            label='Familia',
            field_type='text',
            required=True,
            help_text='ID familia. Se usará como filtro principal de reglas.',
        ),
        FieldDefinition(
            name='rule_name',
            label='Regla',
            field_type='text',
            required=True,
            help_text='Nombre enfocable/operacional de la regla.',
        ),
        FieldDefinition(
            name='display_name',
            label='Nombre visible',
            field_type='text',
            required=True,
        ),
        FieldDefinition(
            name='title_template',
            label='Título',
            field_type='text',
            required=False,
        ),
        FieldDefinition(
            name='cause_template',
            label='Causa',
            field_type='text',
            required=False,
        ),
        FieldDefinition(
            name='content_key',
            label='ID mensajes/imágenes',
            field_type='text',
            required=False,
            help_text='Clave para conectar esta regla con mensajes e imágenes existentes.',
        ),
        FieldDefinition(
            name='dashboard_group_name',
            label='Grupo dashboard',
            field_type='text',
            required=False,
        ),
        FieldDefinition(
            name='kind',
            label='Tipo',
            field_type='select',
            required=True,
            options=(
                FieldOption(label='Riesgo', value='risk'),
                FieldOption(label='Impacto', value='impact'),
            ),
            default_value='risk',
        ),
        FieldDefinition(
            name='risk_level',
            label='Nivel riesgo',
            field_type='select',
            required=True,
            options=(
                FieldOption(label='1 - Crítico / Nivel 0 inmediato', value='1'),
                FieldOption(label='2 - Escalamiento por tiempo', value='2'),
                FieldOption(label='3 - Sin escalamiento', value='3'),
            ),
            default_value='3',
        ),
        FieldDefinition(
            name='priority_scope_key',
            label='Scope prioridad',
            field_type='text',
            required=True,
        ),
        FieldDefinition(
            name='priority_order',
            label='Prioridad',
            field_type='number',
            required=True,
            default_value=100,
            help_text='Menor número = mayor prioridad dentro del scope.',
        ),
        FieldDefinition(
            name='management_scope_key',
            label='Scope gestión',
            field_type='text',
            required=True,
        ),
        FieldDefinition(
            name='origin_tool_key',
            label='Herramienta inicial',
            field_type='text',
            required=True,
        ),
        FieldDefinition(
            name='operator_bucket',
            label='Bucket operador',
            field_type='text',
            required=False,
            default_value='default',
        ),
        FieldDefinition(
            name='color',
            label='Color',
            field_type='text',
            required=False,
            help_text='Token o color hex. Ejemplo: danger, warning, #dc3545.',
        ),
        FieldDefinition(
            name='hide_all_tools_when_managed',
            label='Ocultar al gestionar',
            field_type='boolean',
            required=True,
            default_value=True,
        ),
        FieldDefinition(
            name='reappear_if_still_active_enabled',
            label='Reaparece si sigue activa',
            field_type='boolean',
            required=True,
            default_value=True,
        ),
        FieldDefinition(
            name='reappear_after_management_minutes',
            label='Reaparecer después de gestión',
            field_type='number',
            required=False,
            default_value=60,
        ),
        FieldDefinition(
            name='reappear_tool_policy',
            label='Reaparece en',
            field_type='select',
            required=True,
            options=(
                FieldOption(label='Herramienta inicial', value='origin_tool'),
                FieldOption(label='Última herramienta visible', value='last_visible_tool'),
                FieldOption(label='Herramienta fija', value='fixed_tool'),
            ),
            default_value='origin_tool',
        ),
        FieldDefinition(
            name='reappear_tool_key',
            label='Herramienta fija reaparición',
            field_type='text',
            required=False,
        ),
        FieldDefinition(
            name='continue_escalation_clock_when_hidden',
            label='Continuar reloj oculta',
            field_type='boolean',
            required=True,
            default_value=True,
        ),
        FieldDefinition(
            name='reappear_if_unmanaged_enabled',
            label='Reaparece si nadie gestiona',
            field_type='boolean',
            required=True,
            default_value=False,
        ),
        FieldDefinition(
            name='reappear_after_unmanaged_minutes',
            label='Reaparecer sin gestión después de',
            field_type='number',
            required=False,
        ),
        FieldDefinition(
            name='use_message_management_override',
            label='Usar reglas del mensaje',
            field_type='boolean',
            required=True,
            default_value=True,
        ),
        FieldDefinition(
            name='escalation_summary',
            label='Escalamiento',
            field_type='text',
            required=False,
            editable=False,
        ),
        FieldDefinition(
            name='visual_summary',
            label='Visualización',
            field_type='text',
            required=False,
            editable=False,
        ),
        FieldDefinition(
            name='is_active',
            label='Activa',
            field_type='boolean',
            required=True,
            default_value=True,
        ),
    ),
)
