from __future__ import annotations

from src.features.configuration.alarm.options import (
    ALARM_BUSINESS_CATEGORY_OPTIONS,
    ALARM_COLOR_OPTIONS,
    ALARM_CRITICALITY_OPTIONS,
    ALARM_KIND_OPTIONS,
    ALARM_VISIBILITY_MODE_OPTIONS,
    AlarmBusinessCategory,
    AlarmColor,
    AlarmCriticality,
    AlarmKind,
    AlarmVisibilityMode,
)
from src.features.configuration.models import AdminSchema, FieldDefinition

ALARM_RULES_ADMIN_SCHEMA = AdminSchema(
    key='alarm_rules',
    title='Reglas de alarmas',
    fields=(
        FieldDefinition(
            name='rule_key',
            label='ID regla',
            field_type='text',
            required=True,
            editable=False,
        ),
        FieldDefinition(
            name='family_key',
            label='Familia',
            field_type='text',
            required=True,
            help_text='ID familia. La familia aporta área operacional y categoría base.',
        ),
        FieldDefinition(
            name='rule_name',
            label='Regla',
            field_type='text',
            required=True,
        ),
        FieldDefinition(
            name='display_name',
            label='Nombre visible',
            field_type='text',
            required=True,
        ),
        FieldDefinition(
            name='title_template',
            label='Título',
            field_type='text',
            required=False,
        ),
        FieldDefinition(
            name='cause_template',
            label='Causa',
            field_type='text',
            required=False,
        ),
        FieldDefinition(
            name='content_key',
            label='ID contenido',
            field_type='text',
            required=True,
            editable=True,
            help_text='ID reusable para mensajes, imágenes y contenido. Varias reglas pueden compartirlo.',
        ),
        FieldDefinition(
            name='kind',
            label='Tipo',
            field_type='select',
            required=True,
            options=ALARM_KIND_OPTIONS,
            default_value=AlarmKind.RISK.value,
        ),
        FieldDefinition(
            name='criticality_code',
            label='Criticidad',
            field_type='select',
            required=True,
            options=ALARM_CRITICALITY_OPTIONS,
            default_value=AlarmCriticality.C3.value,
        ),
        FieldDefinition(
            name='business_category',
            label='Categoría negocio',
            field_type='select',
            required=True,
            options=ALARM_BUSINESS_CATEGORY_OPTIONS,
            default_value=AlarmBusinessCategory.OPERATIONAL.value,
            help_text='Categoría final explícita de la regla.',
        ),
        FieldDefinition(
            name='visibility_mode',
            label='Visibilidad',
            field_type='select',
            required=True,
            options=ALARM_VISIBILITY_MODE_OPTIONS,
            default_value=AlarmVisibilityMode.VISIBLE.value,
            help_text='Solo trazabilidad procesa la regla, pero no la proyecta a colas ni vistas.',
        ),
        FieldDefinition(
            name='scope_key',
            label='Scope prioridad/gestión',
            field_type='text',
            required=True,
            help_text='Scope donde la regla compite por prioridad y donde aplica gestión/desactivación.',
        ),
        FieldDefinition(
            name='priority_order',
            label='Prioridad',
            field_type='number',
            required=True,
            default_value=100,
            help_text='Menor número = mayor prioridad dentro del scope.',
        ),
        FieldDefinition(
            name='origin_tool_key',
            label='Herramienta inicial',
            field_type='text',
            required=True,
        ),
        FieldDefinition(
            name='operator_bucket',
            label='Bucket operador',
            field_type='text',
            required=False,
            default_value='default',
        ),
        FieldDefinition(
            name='color',
            label='Color',
            field_type='select',
            required=True,
            options=ALARM_COLOR_OPTIONS,
            default_value=AlarmColor.YELLOW.value,
        ),
        FieldDefinition(
            name='reappear_if_still_active_enabled',
            label='Reaparece si sigue activa',
            field_type='boolean',
            required=True,
            default_value=True,
        ),
        FieldDefinition(
            name='reappear_after_management_minutes',
            label='Reaparecer después de gestión',
            field_type='number',
            required=False,
            default_value=60,
        ),
        FieldDefinition(
            name='continue_escalation_clock_when_hidden',
            label='Continuar reloj oculta',
            field_type='boolean',
            required=True,
            default_value=True,
        ),
        FieldDefinition(
            name='use_message_management_override',
            label='Usar reglas del mensaje',
            field_type='boolean',
            required=True,
            default_value=True,
        ),
        FieldDefinition(
            name='escalation_summary',
            label='Escalamiento',
            field_type='text',
            required=False,
            editable=False,
        ),
        FieldDefinition(
            name='visual_summary',
            label='Visualización',
            field_type='text',
            required=False,
            editable=False,
        ),
        FieldDefinition(
            name='is_active',
            label='Activa',
            field_type='boolean',
            required=True,
            default_value=True,
            help_text='Si está inactiva, la regla no se evalúa.',
        ),
    ),
)